[vxl] numeric limits <limits> was not included
This caused a compile error in ubuntu 22.04, namely:
 error: ‘numeric_limits’ is not a member of ‘std’